### PR TITLE
Initial directory structure and design doc template

### PR DESCRIPTION
**Pull request by philipwjones**
This is the directory structure proposed in our planning docs. I'm still open to renaming the infrastructure directories (now base and infra).  Also included is a restructuredText template for requirement/design docs.

### CODE REVIEW

**Review by sarats — APPROVED** [review]
Looks good. 

Do you already have readthedocs integration setup to generate the docs? Does that make sense or do we plan to use a different workflow for docs?

**Comment by rljacob** [comment]
A phase 3 task in IG is to figure out a system for all the components to use to do documentation of their models (with auto-display on readthedocs, etc.).  Maybe this is the set up everyone else follows?

**Comment by xylar** [comment]
I would discourage using ReadTheDocs.  Rather than going into it here, I will save that for an appropriate meeting.  The gist, though, is that ReadTheDocs' bots have very limited memory and handle past versions in strange ways that make fixing documentation difficult.

**Review by xylar — APPROVED** [review]
@philipwjones, this looks excellent to me.

It looks like file naming convention will be C++-style mixed case.

**Comment by philipwjones** [comment]
Yeah, I did these with reStructuredText assuming a Sphinx or ReadTheDocs approach. I'm not stuck on that, but if we decide that a solution requiring Markdown is more appropriate, we should maybe decide soon before we create too many of these.

And yes, @xylar the llvm coding style we had proposed uses CamelCase for variables, types, classes so doing the same with filenames for consistency.

**Comment by xylar** [comment]
I should clarify that I am 100% in favor of using reStructuredText, Sphinx and the ReadTheDocs template for documentation.  I just am not onboard with using ReadTheDocs as the hosting site for the docs, as I've had a series of bad experiences with that.

**Comment by jedbrown** [comment]
I'm a big fan of MyST unless everyone on your team loves rST and doesn't write much markdown. 
https://myst-parser.readthedocs.io/en/latest/

**Comment by xylar** [comment]
@jedbrown, I'd be keen to give MyST consideration.  I tend to prefer markdown but had run into trouble with it not quite being capable enough for documentation so it'd be good to have an alternative.

@rljacob, this seems like a conversation the whole infrastructure team should have so we don't use different approaches on different pieces of the project.  Presumably, that's already your plan.

**Comment by jedbrown** [comment]
I've migrated a couple projects with significant mathy docs using this tool. There's enough energy behind MyST that I don't have any maintenance/liability concerns in recommending it.  https://github.com/executablebooks/rst-to-myst

**Pull request closed without merging**
